<?php namespace $NAMESPACE_REPOSITORY$;

use Symfony\Component\HttpKernel\Exception\HttpException;
use App\Repositories\$MODEL_NAME$Repository;
use App\Validators\$MODEL_NAME$Validator;
use Illuminate\Contracts\Validation\ValidationException;
use Prettus\Validator\Exceptions\ValidatorException;

class $MODEL_NAME$Service
{
    protected $repository;
    protected $validator;
    /**
     * ClientService constructor.
     * @param $repository
     */
    public function __construct($MODEL_NAME$Repository $repository, $MODEL_NAME$Validator $validator)
    {
        $this->repository = $repository;
        $this->validator = $validator;
    }

    public function create (array $data)
    {
        // enviar um email
        // disparar notificação
        // postar um tweet

        try {
            $this->validator->with($data)->passesOrFail();
            return $this->repository->create($data);
        }
        catch (ValidatorException $e) {
            return ['error' => true,
                    'message' => $e->getMessageBag()
            ];
        }

    }

    public function update (array $data, $id)
    {
       try {
            $this->validator->with($data)->passesOrFail();
            return $this->repository->update($data, $id);
        }
        catch (ValidatorException $e) {
            return ['error' => true,
                    'message' => $e->getMessageBag()
            ];
        }
    }

}
